language: python
python:
#  - "2.7"
#  - "3.2"
#  - "3.3"
  - "3.4"
#  - "nightly"
env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8

install:
  -pip install --upgrade pip
  - pip install -q Django==$DJANGO_VERSION
  - pip install flake8
  - pip install coveralls
  - pip install -q -r requirements.txt

before_script:
  - flake8 edc_locator

script: 
  - coverage run --source=edc_locator manage.py test

after_success:
  - coveralls
